// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// match_taxkeys_cpp
Rcpp::DataFrame match_taxkeys_cpp(Rcpp::CharacterVector taxkeys, Rcpp::CharacterVector searchkeys, Rcpp::IntegerVector taxonomicLevel);
RcppExport SEXP _FUNGuildR_match_taxkeys_cpp(SEXP taxkeysSEXP, SEXP searchkeysSEXP, SEXP taxonomicLevelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type taxkeys(taxkeysSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type searchkeys(searchkeysSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type taxonomicLevel(taxonomicLevelSEXP);
    rcpp_result_gen = Rcpp::wrap(match_taxkeys_cpp(taxkeys, searchkeys, taxonomicLevel));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FUNGuildR_match_taxkeys_cpp", (DL_FUNC) &_FUNGuildR_match_taxkeys_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_FUNGuildR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
