# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

match_taxkeys_cpp <- function(taxkeys, searchkeys, taxonomicLevel) {
    .Call(`_FUNGuildR_match_taxkeys_cpp`, taxkeys, searchkeys, taxonomicLevel)
}

